/**
 * @file Tests for MockLlmProvider adapter.
 */

import { describe, it, expect } from 'vitest';
import { MockLlmProvider } from '../../../src/infrastructure/llm/MockLlmProvider.js';
import { ILlmProvider } from '../../../src/application/ports/ILlmProvider.js';
import { GenerationRequest } from '../../../src/domain/value-objects/GenerationRequest.js';

describe('MockLlmProvider', () => {
    /**
     * Test that provider extends ILlmProvider.
     */
    it('should extend ILlmProvider', () => {
        const provider = new MockLlmProvider();
        expect(provider).toBeInstanceOf(ILlmProvider);
    });

    /**
     * Test default mock response.
     */
    it('should return default mocked response', async () => {
        const provider = new MockLlmProvider();
        const request = new GenerationRequest({
            systemPrompt: 'Test system',
            userPrompt: 'Test user',
        });

        const response = await provider.generate(request);
        const parsed = JSON.parse(response);

        expect(parsed.name).toBe('MockCharacter');
        expect(parsed.description).toBe('A character generated by MockLlmProvider');
        expect(parsed.personality).toBe('Helpful and friendly');
        expect(parsed.scenario).toBe('In a test environment');
        expect(parsed.first_mes).toBe('Hello! I am a mock character.');
        expect(parsed.mes_example).toBe('This is an example message.');
    });

    /**
     * Test that response is valid JSON.
     */
    it('should return valid JSON', async () => {
        const provider = new MockLlmProvider();
        const request = new GenerationRequest({
            systemPrompt: 'Test',
            userPrompt: 'Test',
        });

        const response = await provider.generate(request);
        expect(() => JSON.parse(response)).not.toThrow();
    });

    /**
     * Test that response contains required character fields.
     */
    it('should return response with required character fields', async () => {
        const provider = new MockLlmProvider();
        const request = new GenerationRequest({
            systemPrompt: 'Test',
            userPrompt: 'Test',
        });

        const response = await provider.generate(request);
        const parsed = JSON.parse(response);

        const required = ['name', 'description', 'personality', 'scenario', 'first_mes', 'mes_example'];
        for (const field of required) {
            expect(parsed).toHaveProperty(field);
            expect(typeof parsed[field]).toBe('string');
        }
    });
});
