/**
 * @file Adapter that returns canned responses for testing and demo purposes.
 */

import { ILlmProvider } from '../../application/ports/ILlmProvider.js';

/**
 * Mock LLM provider that returns preset responses.
 *
 * @augments ILlmProvider
 */
export class MockLlmProvider extends ILlmProvider {
    /**
     * Construct with mock response data.
     *
     * @param {object} [mockResponses] - map of prompt patterns to canned responses
     */
    constructor(mockResponses = {}) {
        super();
        this.mockResponses = mockResponses;
    }

    /**
     * Return a mock response based on the request.
     *
     * @param {import('../../application/ports/ILlmProvider.js').GenerationRequest} _request - generation parameters
     * @returns {Promise<string>} mocked generated text
     */
    async generate(_request) {
        const defaultResponse = {
            name: 'MockCharacter',
            description: 'A character generated by MockLlmProvider',
            personality: 'Helpful and friendly',
            scenario: 'In a test environment',
            first_mes: 'Hello! I am a mock character.',
            mes_example: 'This is an example message.',
        };

        return JSON.stringify(defaultResponse);
    }
}
